language: erlang
notifications:
  email: paul.joseph.davis@gmail.com
script: make check
otp_release:
   - 17.5
   - 17.4
   - 17.3
   - 17.1
   - 17.0
   - R16B03-1
   - R16B02
   - R16B01
   - R15B03
   - R15B02
   - R15B01
   - R14B04
   - R14B03
   - R14B02
